site_name: University of Minnesota Senior Projects
site_description: 'DESCRIPTION All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/u-of-mn-senior-projects/'
repo_url: 'https://github.com/dmccreary/u-of-mn-senior-projects'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Intelligent Textbooks Proposal: intelligent-textbooks-proposal.md
  - Glossary: glossary.md
  - References: references.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  # logo: img/logo.png
  # favicon: img/my-icon.png
  palette:
    primary: custom
    accent: 'gold'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
extra_javascript:
    - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX